# Generated by Django 5.2 on 2025-05-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChiPhi",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ten", models.CharField(max_length=100)),
                ("loai", models.CharField(blank=True, max_length=100, null=True)),
                ("donvi", models.CharField(max_length=50)),
                ("gia", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mota", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KhachThue",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("hoten", models.CharField(max_length=100)),
                ("ngaysinh", models.DateField()),
                ("diachi", models.CharField(max_length=200)),
                ("cccd", models.CharField(max_length=100)),
                ("dienthoai", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhongTro",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("sophong", models.CharField(max_length=100)),
                ("diachi", models.CharField(blank=True, max_length=200, null=True)),
                ("mota", models.TextField(blank=True, null=True)),
                (
                    "dientich",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "giaphong",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("loaiphong", models.CharField(blank=True, max_length=50, null=True)),
                ("trangthai", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HopDong",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ngaybatdau", models.DateField()),
                ("ngayketthuc", models.DateField()),
                ("tiencoc", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "khachthue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phongtro.khachthue",
                    ),
                ),
                (
                    "phongtro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phongtro.phongtro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HoaDon",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ngaythanhtoan", models.DateField(blank=True, null=True)),
                ("trangthai", models.CharField(max_length=50)),
                ("tonghoadon", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ngaytao", models.DateField(auto_now_add=True)),
                (
                    "khachthue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phongtro.khachthue",
                    ),
                ),
                (
                    "phongtro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phongtro.phongtro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SinhHoat",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("dien", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nuoc", models.DecimalField(decimal_places=2, max_digits=10)),
                ("internet", models.IntegerField()),
                ("giatdo", models.IntegerField()),
                ("rac", models.IntegerField()),
                (
                    "khachthue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phongtro.khachthue",
                    ),
                ),
                (
                    "phongtro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phongtro.phongtro",
                    ),
                ),
            ],
        ),
    ]
