# Generated by Django 5.2 on 2025-06-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KhachThue",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("hoten", models.CharField(max_length=100)),
                ("ngaysinh", models.DateField()),
                ("diachi", models.CharField(max_length=200)),
                ("cccd", models.CharField(max_length=100)),
                ("dienthoai", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhongTro",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("diachi", models.CharField(blank=True, max_length=200, null=True)),
                ("mota", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "dientich",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "giaphong",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "loaiphong",
                    models.CharField(
                        choices=[
                            ("Phòng đơn", "Phòng đơn"),
                            ("Phòng đôi", "Phòng đôi"),
                        ],
                        default="Phòng đôi",
                        max_length=10,
                    ),
                ),
                (
                    "trangthai",
                    models.CharField(
                        choices=[("Trống", "Trống"), ("Đã thuê", "Đã thuê")],
                        default="Trống",
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HopDong",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ngaybatdau", models.DateField()),
                ("ngayketthuc", models.DateField()),
                (
                    "khachthue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phongtro.khachthue",
                    ),
                ),
                (
                    "phongtro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phongtro.phongtro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HoaDon",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ngaythanhtoan", models.DateField(blank=True, null=True)),
                (
                    "trangthai",
                    models.CharField(
                        choices=[
                            ("Đã thanh toán", "Đã thanh toán"),
                            ("Chưa thanh toán", "Chưa thanh toán"),
                        ],
                        default="Chưa thanh toán",
                        max_length=50,
                    ),
                ),
                ("tonghoadon", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ngaytao", models.DateField(auto_now_add=True)),
                ("hoaDonCuaThangNam", models.DateField(blank=True, null=True)),
                (
                    "khachthue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phongtro.khachthue",
                    ),
                ),
                (
                    "phongtro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phongtro.phongtro",
                    ),
                ),
            ],
        ),
    ]
